### ISSUE TITLE
CodingRoads ouvre ses portes !

### ISSUE THREAD

**Issue by Pyrrha** [Liftiz/Blanc-Marie#1]
Bonjour @Liftiz,

Voudrais-tu nous rejoindre sur le nouveau serveur Discord ?
https://discord.gg/5jzDgB

Bien à toi,

Pyrrha

**Comment by Deimz** [comment]
Helloooo  ,

Les relous sont plus là,  le nouveau serveur où on attends que toi est la : https://discord.gg/5jzDgB

On espere te voir soon ! 

Force & Honneur @Liftiz 

Deimz
